title: Yağmur Ayaydın / Animation and Art Portfolio
description: Artist • Indie Game Dev • Animator
theme: minima
header_pages:
  - about.md
  - portfolio.md layout: page
  header_pages:
  - about.md
  - portfolio.md
author: Yağmur Ayaydın
github_username: fablemist
show_excerpts: true
