title: "Yağmur Ayaydın / Animation and Art Portfolio"
description: "Artist • Indie Game Dev • Animator"
theme: minima

sass:
  style: compressed

header_pages:
  - index.md
  - about.md
  - portfolio.md

author: "Yağmur Ayaydın"
github_username: fablemist
show_excerpts: true
